export const FETCH_MANUFACTURERS = 'FETCH_MANUFACTURERS';
export const FETCH_COLORS= 'FETCH_COLORS';
export const SET_MANUFACTURER = 'SET_MANUFACTURER';
export const SET_COLOR = 'SET_COLOR';
export const SET_ORDER = 'SET_ORDER';
export const FILTER_DATA = 'FILTER_DATA';